"""create_technologies

Revision ID: f4577bb3e45c
Revises: 17b191d162a9
Create Date: 2021-06-10 00:31:09.428489

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f4577bb3e45c'
down_revision = '17b191d162a9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('url_name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_url_name'), 'technologies', ['url_name'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technologies_url_name'), table_name='technologies')
    op.drop_table('technologies')
    # ### end Alembic commands ###
