"""create_projects

Revision ID: 17b191d162a9
Revises: 
Create Date: 2021-06-09 23:48:14.519773

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '17b191d162a9'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('url_name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_url_name'), 'projects', ['url_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_url_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
