"""add_icon_url_to_technologies

Revision ID: 242bd665c08a
Revises: aae63862196e
Create Date: 2021-11-19 00:44:45.774327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242bd665c08a'
down_revision = 'aae63862196e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technologies', sa.Column('icon_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technologies', 'icon_url')
    # ### end Alembic commands ###
